//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMaylin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdProyectoWeb_MaylinCruzEntities : DbContext
    {
        public bdProyectoWeb_MaylinCruzEntities()
            : base("name=bdProyectoWeb_MaylinCruzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCitizen> tblCitizens { get; set; }
        public virtual DbSet<tblDocument> tblDocuments { get; set; }
        public virtual DbSet<tblDocumentXCitizen> tblDocumentXCitizens { get; set; }
        public virtual DbSet<tblRol> tblRols { get; set; }
        public virtual DbSet<tblTransport> tblTransports { get; set; }
        public virtual DbSet<tblTransportXCitizen> tblTransportXCitizens { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
