//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMaylin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCitizen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCitizen()
        {
            this.tblDocumentXCitizens = new HashSet<tblDocumentXCitizen>();
            this.tblTransportXCitizens = new HashSet<tblTransportXCitizen>();
        }
    
        public int cit_id { get; set; }
        public string cit_name { get; set; }
        public string cit_lastname { get; set; }
        public Nullable<System.DateTime> cit_birthdate { get; set; }
        public Nullable<int> cit_age { get; set; }
        public string cit_gender { get; set; }
        public string cit_telephone { get; set; }
        public string cit_direction { get; set; }
        public string cit_bloodType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentXCitizen> tblDocumentXCitizens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransportXCitizen> tblTransportXCitizens { get; set; }
    }
}
