//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMaylin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumentXCitizen
    {
        public int DoCi_id { get; set; }
        public Nullable<int> doc_id { get; set; }
        public Nullable<int> cit_id { get; set; }
        public Nullable<bool> DoCi_StatusExamenOral { get; set; }
        public Nullable<bool> DoCi_StatusExamenPractico { get; set; }
        public Nullable<System.DateTime> DoCi_DateOfIssue { get; set; }
        public Nullable<System.DateTime> DoCi_FinishDate { get; set; }
    
        public virtual tblCitizen tblCitizen { get; set; }
        public virtual tblDocument tblDocument { get; set; }
    }
}
