//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMaylin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportXCitizen
    {
        public int TrCi_id { get; set; }
        public Nullable<int> tra_id { get; set; }
        public Nullable<int> cit_id { get; set; }
        public string TrCi_brand { get; set; }
        public string TrCi_model { get; set; }
        public string TrCi_plate { get; set; }
        public Nullable<int> TrCi_year { get; set; }
    
        public virtual tblCitizen tblCitizen { get; set; }
        public virtual tblTransport tblTransport { get; set; }
    }
}
