//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMaylin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int use_id { get; set; }
        public string use_idnumber { get; set; }
        public string use_name { get; set; }
        public string use_lastname { get; set; }
        public string use_nickname { get; set; }
        public string use_password { get; set; }
        public string use_gender { get; set; }
        public string use_email { get; set; }
        public string use_telephone { get; set; }
        public Nullable<int> use_rol { get; set; }
    
        public virtual tblRol tblRol { get; set; }
    }
}
